config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :reports

  resources :traps

end

app/models/notifier.rb
class Notifier
  include ActionView::Helpers::DateHelper

  def send_notifications
    trap_alerts = {}

    Trap.all.each do |trap|
      alerts = alerts_for_trap(trap)
      trap_alerts[trap.id] = alerts unless alerts.blank?
    end

    unless trap_alerts.empty?
      User.all.each do |user|
        email = NotificationMailer.notification_email(user, trap_alerts)
        email.deliver_now
      end
    end
  end

  private
  def alerts_for_trap(trap)
    alerts = []

    last_report = trap.last_report
    if last_report.present? && last_report.sent_at < 3.days.ago
      time_distance = distance_of_time_in_words(Time.now, last_report.sent_at)
      alerts << "quiet since #{time_distance} ago"
    end

    if trap.bait_level < 20
      alerts << ("bait level at %.2f%%" % [trap.bait_level])
    end

    if trap.battery_level < 4.2
      alerts << "battery level low"
    end

    return alerts
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :trap

  validates_presence_of :trap_id, :sent_at

  def sent_at=(value)
    value = Time.at(value) if value.is_a? Numeric
    super(value)
  end
end

app/models/report_chunk.rb
class ReportChunk < ActiveRecord::Base
  CHUNK_TYPES = {
    battery_level:  1,
    bait_level:     2
  }.freeze

  belongs_to :trap

  validates_presence_of :trap_id, :chunk_type, :generated_at, :data
  validates_uniqueness_of :generated_at, scope: [:trap_id, :chunk_type]

  serialize :data, Hash

  def generated_at=(value)
    value = Time.at(value) if value.is_a? Numeric
    super(value)
  end
end

app/models/trap.rb
class Trap < ActiveRecord::Base
  has_many :reports, dependent: :destroy
  has_many :report_chunks, dependent: :destroy

  def battery_level
    report_chunks
      .where(chunk_type: ReportChunk::CHUNK_TYPES[:battery_level])
      .order('generated_at DESC')
      .limit(1)
      .first.data[:level] / 1000.0
  end

  def bait_level
    report_chunks
      .where(chunk_type: ReportChunk::CHUNK_TYPES[:bait_level])
      .order('generated_at DESC')
      .limit(10) # WARNING: This makes assumptions
      .group_by{|chunk| chunk.data[:bait_id]}
      .map{|k, vs| [k, vs.first.data[:level]]}
      .sort_by(&:second).first.second
  end

  def last_report
    reports.order('sent_at').last
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  UDP_SERVER_ACTIONS = [:create]

  skip_before_filter :verify_authenticity_token, only: UDP_SERVER_ACTIONS
  http_basic_authenticate_with name: ENV['UDP_AUTH_USER'],
    password: ENV['UDP_AUTH_PASS'], only: UDP_SERVER_ACTIONS
  before_action :authenticate_user!, except: UDP_SERVER_ACTIONS

  def create
    @report = Report.new(report_params)

    unless Trap.where(id: @report.trap_id).any?
      Trap.create(id: @report.trap_id)
    end

    @report.save

    params.fetch(:chunks, []).each do |chunk_hash|
      report_chunk = ReportChunk.new(chunk_params(chunk_hash).merge(trap_id: @report.trap_id))
      if report_chunk.valid?
        report_chunk.save
      end
    end

    render plain: "OK"
  end

  def index
    @reports = Report.order(created_at: :desc)
  end

  private
  def report_params
   params.require(:report).permit(
     :original_message, :protocol_version, :trap_id, :sent_at)
  end

  def chunk_params(hash)
    ActionController::Parameters.new(chunk: hash).require(:chunk)
      .tap do |whitelisted|
        [:chunk_type, :generated_at, :data].each do |key|
          whitelisted[key] = hash[key]
        end
      end
      .permit!
  end
end

app/controllers/traps_controller.rb
class TrapsController < ApplicationController
  before_action :authenticate_user!

  def index
    @traps = Trap.all
  end

  def show
    @trap = Trap.find(params[:id])

    @report_chunks = @trap.report_chunks
      .where('generated_at >= ?', 1.year.ago)
      .order('generated_at')
  end

  def destroy
    @trap = Trap.find(params[:id])
    @trap.destroy

    flash[:notice] = "Data for trap ##{params[:id]} deleted successfully."
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, '×'.html_safe, class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

  def pretty_time(time)
    time.in_time_zone("Australia/Melbourne").strftime("%B %e, %Y %l:%M%P")
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/traps_helper.rb
module TrapsHelper
  def bait_level_chart(report_chunks)
    bait_data = report_chunks
      .select {|chunk| chunk.chunk_type == ReportChunk::CHUNK_TYPES[:bait_level]}
      .map do |chunk|
        [chunk.data[:bait_id], chunk.generated_at.to_i * 1000, chunk.data[:level]]
      end
      .group_by(&:first)
      .map do |(bait_id, rows)|
        [bait_id, rows.map {|r| r[1..-1]}]
      end

    graph = time_series_graph do |f|
      f.yAxis title: {text: 'Bait level (%)'}, min: 0, max: 100
      f.legend enabled: true
      bait_data.each do |(bait_id, series_data)|
        f.series(name: "Bait ##{bait_id}", type: 'area', data: series_data)
      end
    end

    high_chart("bait_chart", graph)
  end

  def battery_level_chart(report_chunks)
    battery_data = report_chunks
      .select {|chunk| chunk.chunk_type == ReportChunk::CHUNK_TYPES[:battery_level]}
      .map do |chunk|
        [chunk.generated_at.to_i * 1000, chunk.data[:level] / 1000.0]
      end

    graph = time_series_graph do |f|
      f.yAxis title: {text: 'Battery level (V)'}, min: 0, max: 6
      f.legend enabled: false
      f.series(type: 'area', data: battery_data)
    end

    high_chart("battery_chart", graph)
  end

  private

  def time_series_graph
    LazyHighCharts::HighChart.new('graph') do |f|
      f.chart type: 'line', borderWidth: '1',
        spacingBottom: 20, spacingTop: 20,
        spacingLeft: 20, spacingRight: 20
      f.xAxis title: {text: 'Time'}, type: 'datetime'

      yield f
    end
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title= content_for?(:page_title) ? yield(:page_title) : 'RatTrace'
    - if content_for?(:page_description)
      %meta{name: 'description', content: yield(:page_description)}
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true)
    = javascript_include_tag('application', 'data-turbolinks-track' => true)
    = csrf_meta_tags
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
  %body
    .wrapper
      .container
        %nav.navbar.navbar-default
          .container-fluid
            .navbar-header
              %a.navbar-brand{href: root_url}
                %span.glyphicon.glyphicon-home
                %span{style: 'padding-left: 8px;'} RatTrace
              %button.navbar-toggle.collapsed{type: "button", "data-toggle": "collapse", "data-target": "#nav-collapse-1"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
            - if user_signed_in?
              %div#nav-collapse-1.collapse.navbar-collapse
                .nav.navbar-nav.navbar-right
                  %p.navbar-text
                    Signed in as
                    = link_to current_user.email, edit_user_registration_url(current_user)
      %main
        = content_for :heading
        .container
          - flash_messages
        = yield
    %footer.footer
      .container
        .row
          .col-sm-9
            .row
              .col-xs-3
                %span.link-list-heading RatTrace
                %ul.link-list
                  %li= link_to "Home", root_url
                  %li= link_to "About us", root_url
              .col-xs-3
                %span.link-list-heading Product
                %ul.link-list
                  %li
                    %a{href: "#"} Features
                  %li
                    %a{href: "#"} Pricing
              .col-xs-3
                %span.link-list-heading Support
                %ul.link-list
                  %li
                    %a{href: "#"} Contact
              .col-xs-3
                %span.link-list-heading Members
                %ul.link-list
                  - if user_signed_in?
                    %li= link_to "Log out", destroy_user_session_url, method: 'delete'
                    %li= link_to "Edit account", edit_user_registration_url
                  - else
                    %li= link_to "Sign up", new_user_registration_url
                    %li= link_to "Log in", new_user_session_url
          .col-sm-3
            RatTrace is a project by
            = succeed(",") do
              - link_to "Aiden Nibali", "http://aiden.nibali.org/"
            an undergraduate student at
            = succeed(".") do
              - link_to "La Trobe University", "http://www.latrobe.edu.au/"

app/views/pages/home.haml
- content_for :heading do
  .masthead.masthead-thick
    .container.masthead-inner
      .row
        .col-sm-8.masthead-image
          %img{src: image_url("masthead_rat.png")}
        .col-sm-4.masthead-text
          %p.masthead-heading
            RatTrace
          %p
            An intelligent rat trap monitoring solution for the next generation of
            pest control.

.container.text-section
  %p
    Rats, especially Norway rats and roof rats, are nasty pests that
    spread disease,
    contaminate food and water,
    consume food supplies, and
    cause property damage.
  %p
    Pest control experts do a great job of managing rodent populations through the deployment of rat bait traps. Unfortunately, checking to see which traps need to have their bait replenished for continued operation is a time-consuming chore - someone has to physically travel to the location of each trap and visually inspect the bait.
    %em This is highly inefficient.
  %p
    RatTrace improves operational efficiency for pest control companies by enabling remote monitoring of bait stations. A small electronic device is retrofitted to existing traps, and this device is able to transmit trap status data wirelessly to a central server. Forget about inspecting traps manually, RatTrace can
    %em tell you
    which bait stations require servicing!

app/views/reports/index.haml
- content_for :heading do
  .masthead
    .container
      %h1 Reports
      %p
        A list of all of the automatic trap reports currently stored in the
        database, grouped by date.

.container.text-section
  - @reports.group_by{|r| r.created_at.to_date}.each do |date, reports|
    %h2= date
    %table.table
      %tr
        - Report.column_names.each do |col|
          %th= col
      - reports.each do |report|
        %tr
          - Report.column_names.each do |col|
            - if col == "original_message"
              %td
                = report[col]
                %br
                %small= Base64.decode64(report[col]).inspect
            - else
              %td= report[col]

app/views/traps/index.haml
- content_for :heading do
  .masthead
    .container
      %h1= "Traps"
      %p
        A list of all traps with data available.

.container.text-section
  %ul
    - @traps.each do |trap|
      %li= link_to "Trap ##{trap.id}", trap_url(trap)

app/views/traps/show.haml
- content_for :heading do
  .masthead
    .container
      %h1= "Trap ##{@trap.id}"
      %p
        A summary of information about this trap.

.container.text-section
  %h2 Quick stats
  .panel.panel-default.table-responsive
    %table.table
      %thead
        %tr
          %th Battery
          %th Bait
          %th Last report
      %tbody
        %tr
          %td= "%.2fV" % [@trap.battery_level]
          %td= "%.2f%%" % [@trap.bait_level]
          %td= pretty_time(@trap.last_report.sent_at)
  %h2 Bait level history
  = bait_level_chart(@report_chunks)
  %h2 Battery level history
  = battery_level_chart(@report_chunks)
  %p
    %div.pull-right
      = button_to "Delete all data", trap_url(@trap), data: { confirm: "Permanently delete all data for this trap?" }, method: :delete, class: "btn btn-danger"